sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - valgrind
      - cppheck
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - make -C examples/travis-identifier/ run_cppcheck
#  - make test
